### ISSUE TITLE
400 Bad Request: missing required Host header

### ISSUE THREAD

**Issue by poteirard** [jolicode/JoliCi#75] opened 2016-10-05 10:54 UTC
I'm trying to get started with JoliCi but it give me an error:

<img width="1169" alt="1__gbrull_gerard-brull-en4____projects_github_temporary-filesystem__zsh_" src="https://cloud.githubusercontent.com/assets/7198934/19110550/e23fb93e-8afa-11e6-88ae-6abb61359fbe.png">

Any ideas?

**Comment by serhiicherepanov** [comment] 2016-11-08 08:24
Some issue on **macOS Sierra**

docker -v:

```
Docker version 1.12.1, build 6f9534c
```

php -v:

```
HP 7.0.8 (cli) (built: Jul 16 2016 23:58:10) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.13.0, https://blackfire.io, by Blackfireio Inc.
```

**Comment by mglaman** [comment] 2016-11-17 16:47
The issue is `docker-php`

**Comment by mglaman** [comment] 2016-11-17 16:52
I wonder if docker-php/docker-php#214 is the solution.

**Comment by mglaman** [comment] 2016-11-17 17:00
Patched with the above, and now it works.

**Comment by taz77** [comment] 2016-11-19 03:21
Confirmed, the problem is docker-php. Exactly what @mglaman stated, the patch in the linked PR fixes the problem.

**Comment by wlalele** [comment] 2016-11-24 08:06
+1

**Comment by ghost** [comment] 2017-12-07 04:57
Fixed upstream, by the looks of it.

**Comment by lyrixx** [comment] 2022-05-25 14:04
Hello, 

Thanks for opening this issue.

Unfortunately, we don't support this repository anymore.
I'm sorry, but I'll close this issue.

I hope you understand.

**Closed as completed by lyrixx** 2022-05-25 14:04 UTC
