### ISSUE TITLE
Cannot open socket connection

### ISSUE THREAD

**Issue by Nek-** [jolicode/JoliCi#42] opened 2015-02-03 15:39 UTC
Hello,

I try to build my project but got the following error. I don't know what happen but my docker is working and permissions are ok to work.

```
Creating builds...
1 builds created

Running job php = 5.4



                                                                     
  [GuzzleHttp\Exception\RequestException]                            
  Cannot open socket connection: No such file or directory [code 2]  
                                                                     


Exception trace:
 () at /home/maxime/.composer/vendor/stage1/docker-php/src/Docker/Http/Adapter/DockerAdapter.php:100
 Docker\Http\Adapter\DockerAdapter->createResponse() at /home/maxime/.composer/vendor/stage1/docker-php/src/Docker/Http/Adapter/DockerAdapter.php:70
 Docker\Http\Adapter\DockerAdapter->send() at /home/maxime/.composer/vendor/guzzlehttp/guzzle/src/Client.php:186
 GuzzleHttp\Client->send() at /home/maxime/.composer/vendor/guzzlehttp/guzzle/src/Client.php:149
 GuzzleHttp\Client->get() at /home/maxime/.composer/vendor/stage1/docker-php/src/Docker/Manager/ImageManager.php:39
 Docker\Manager\ImageManager->findAll() at /home/maxime/.composer/vendor/jolicode/jolici/src/Joli/JoliCi/Vacuum.php:187
 Joli\JoliCi\Vacuum->getJobs() at /home/maxime/.composer/vendor/jolicode/jolici/src/Joli/JoliCi/Vacuum.php:142
 Joli\JoliCi\Vacuum->getJobsToRemove() at /home/maxime/.composer/vendor/jolicode/jolici/src/Joli/JoliCi/Vacuum.php:62
 Joli\JoliCi\Vacuum->clean() at /home/maxime/.composer/vendor/jolicode/jolici/src/Joli/JoliCi/Command/RunCommand.php:74
 Joli\JoliCi\Command\RunCommand->execute() at /home/maxime/.composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /home/maxime/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /home/maxime/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /home/maxime/.composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /home/maxime/.composer/vendor/jolicode/jolici/bin/jolici:28


run [-p|--project-path[="..."]] [-k|--keep[="..."]] [--no-cache] [--timeout[="..."]] [cmd]
```

**Comment by Nek-** [comment] 2015-02-05 15:35
@joelwurtz you need to upgrade to docker-php `~0.4.0` https://github.com/stage1/docker-php/issues/95#issuecomment-73050572

**Comment by clue** [comment] 2015-02-23 10:04
I ran into the same problem and (erroneously) reported it a few months ago in an unrelated ticket: https://github.com/jolicode/JoliCi/issues/34#issuecomment-64685213. I've tracked this down to commit 20c5e3bdde429454157a97b2721b24aab8ec4900, any earlier commit does work fine (and so does the last tagged release).

A copy-pase of @joelwurtz' [response](https://github.com/jolicode/JoliCi/issues/34#issuecomment-64883257):

> JoliCi does not assume default entrypoint by default anymore, so you to have specificy the host of docker:
```
DOCKER_HOST=unix:///var/run/docker.sock ./bin/jolici run -vvv
```

This does indeed work around the issue for me using the current master branch (2641d0d7e3270330ee0921ca86a6f2ccea3008be).

Is this intended behavior to require passing an additional environment variable (BC break ahead) or will this (eventually) be fixed by upgrading the dependencies?

**Comment by clue** [comment] 2015-02-23 10:59
Looks like this issue has indeed been caused by a typo in stage1/docker-php that has been fixed with v0.4.0: https://github.com/stage1/docker-php/commit/f55f61d70e1bcd29d798e1584f7d9557917aae8e

As such, upgrading the dependencies should apparently fix this issue.

**Comment by clue** [comment] 2015-02-25 14:18
Thanks @joelwurtz, the latest commit (6400028f0c4ad83d228114d5306c21c0d3bf562e) supersedes #32 and updates docker-php to v0.4.1.

The error can no longer be reproduced, I suppose this issue can be closed?

**Comment by joelwurtz** [comment] 2015-02-25 15:23
I will close this issue when a new release is deployed for JoliCi (should be tomorrow or friday) so users can use the latest jolici.phar binary

**Comment by joelwurtz** [comment] 2015-02-25 16:02
New version available :)

**Closed by joelwurtz** 2015-02-25 16:02 UTC

**Comment by Nek-** [comment] 2015-02-25 16:03
:+1:
